<?php

/**
 * BranchFiltersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BranchFiltersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BranchFiltersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BranchFilters');
    }
}