<?php

/**
 * LookupShopCategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LookupShopCategoriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LookupShopCategoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LookupShopCategories');
    }
    
    public static function getAllShopCategories($lang_id = 1){
        return Doctrine_Query::create()
                ->select('sc.id, sc.name')
                ->from('LookupShopCategories sc')
                ->where('sc.lang_id=?', $lang_id)
                ->orderBy('sc.name ASC')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
    
    public static function getShopCategories($category_name){
        $category_name = str_replace('%20', ' ', $category_name);
        $q = Doctrine_Query::create()
                ->select('sc.id')
                ->from('LookupShopCategories sc')
                ->where('sc.name=?', trim($category_name))
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->fetchOne();
        return $q['id'];
    }
}