<?php

/**
 * LookupCurrenciesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LookupCurrenciesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LookupCurrenciesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LookupCurrencies');
    }
    
    public static function getCurrencies($lang_id = '1'){
        return Doctrine_Query::create()
                ->select('c.*')
                ->from('LookupCurrencies c')
                ->where('c.lang_id =?', $lang_id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
}