<?php

/**
 * LookupCountriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LookupCountriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LookupCountriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LookupCountries');
    }
    
    public static function listCountries($lang_id){
        return Doctrine_Query::create()
                ->select('c.*')
                ->from('LookupCountries c')
                ->where('c.lang_id=?', $lang_id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
        
    }
}