<?php

/**
 * LookupTemplatesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LookupTemplatesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LookupTemplatesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LookupTemplates');
    }
}