<?php

/**
 * LookupGovernoratesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LookupGovernoratesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LookupGovernoratesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LookupGovernorates');
    }
    
    public static function listGovernorates(){
        return Doctrine_Query::create()
                ->select('g.*')
                ->from('LookupGovernorates g')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
        
    }
}