<?php

/**
 * MobileRegistrationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MobileRegistrationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MobileRegistrationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MobileRegistrations');
    }
}