<?php

/**
 * ProductRatingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductRatingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductRatingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductRating');
    }
    
    public static function getProductRating($shop_id){
        return Doctrine_Query::create()
                ->select('pr.*, r.*, p.name')
                ->from('ProductRating pr, pr.ShopProducts p, p.ShopMenuSubs m, pr.MobileRegistrations r')
                ->where('m.shop_id=?', $shop_id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
}