<?php

/**
 * ProductRating
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductRating extends BaseProductRating
{
    public function rateProduct(array $data){
        $r = new ProductRating();
        $r->mobile_user_id = $data['user_id'];
        $r->product_id = $data['product_id'];
        $r->rating = $data['rating'];
        $r->created_at = date('ymdHis');
        $r->save();
    }
    
    public function getRatingByEmailAndShopId($email, $shop_id){
        return Doctrine_Query::create()
                ->select('r.product_id, r.rating')
                ->from('ProductRating r, r.MobileRegistrations mu, r.ShopProducts p, p.ShopMenuSubs m')
                ->where('mu.email=?', trim($email))
                ->andWhere('m.shop_id=?', trim($shop_id))
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
}