<?php

/**
 * ShopAlbumsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopAlbumsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopAlbumsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopAlbums');
    }
    
    public static function getAllAlbums($shop_id){
        return Doctrine_Query::create()
                ->select('a.*, m.id, s.id')
                ->from('ShopAlbums a, a.ShopMenuSubs m, m.Shops s')
                ->where('s.id=?', $shop_id)
                ->andWhere('a.deleted=0')
                ->orderBy('a.album_order ASC')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
    
    public static function getShopAlbumsImages($shop_id){
        return Doctrine_Query::create()
                ->select('a.*, ai.*, m.id, s.id')
                ->from('ShopAlbums a, a.ShopAlbumImages ai, a.ShopMenuSubs m, m.Shops s')
                ->where('s.id=?', $shop_id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
}