<?php

/**
 * ShopProductComponentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopProductComponentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopProductComponentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopProductComponents');
    }
}