<?php

/**
 * ShopOnlinePresence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShopOnlinePresence extends BaseShopOnlinePresence {

    function addOnlinePresence(array $online_data) {
        foreach($online_data['online_presence'] as $online_presence) {
            $o = new ShopOnlinePresence();
            $o->shop_id = $online_data['shop_id'];
            $o->url = $online_presence;
            $o->created_at = date('ymdHis');
            $o->save();
        }
    }

}