<?php

/**
 * ShopBranches
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShopBranches extends BaseShopBranches {

    public function addBranch(array $branch_data) {
        $sub_id = $branch_data['menu_id'];
        if (isset($branch_data['sub_id'])) {
            $sub_id = $branch_data['sub_id'];
        }
        
        $b = new ShopBranches();
        $b->menu_id = $sub_id;
        $b->collection_id = $branch_data['collection_id'];
        $b->name = $branch_data['name'];
        $b->longitude = $branch_data['longitude'];
        $b->latitude = $branch_data['latitude'];
        $b->city = $branch_data['city'];
        $b->area = $branch_data['area'];
        $b->street_address = $branch_data['street_address'];
        $b->tel1 = $branch_data['tel1'];
        $b->tel2 = $branch_data['tel2'];
        $b->fax = $branch_data['fax'];
        $b->email = $branch_data['email'];
        $b->website = $branch_data['website'];
        $b->is_active = true;
        $b->created_at = date('ymdHis');
        $b->save();
        
        return $b->id;
    }

    public function updateBranch(array $branch_data) {
        $sub_id = $branch_data['menu_id'];
        if (isset($branch_data['sub_id'])) {
            $sub_id = $branch_data['sub_id'];
        }
        
        Doctrine_Query::create()
                ->update('ShopBranches b')
                ->set('b.menu_id', '?', $sub_id)
                ->set('b.collection_id', '?', $branch_data['collection_id'])
                ->set('b.name', '?', $branch_data['name'])
                ->set('b.longitude', '?', $branch_data['longitude'])
                ->set('b.latitude', '?', $branch_data['latitude'])
                ->set('b.city', '?', $branch_data['city'])
                ->set('b.area', '?', $branch_data['area'])
                ->set('b.street_address', '?', $branch_data['street_address'])
                ->set('b.tel1', '?', $branch_data['tel1'])
                ->set('b.tel2', '?', $branch_data['tel2'])
                ->set('b.fax', '?', $branch_data['fax'])
                ->set('b.email', '?', $branch_data['email'])
                ->set('b.website', '?', $branch_data['website'])
                ->set('b.updated_at', '?', date('ymdHis'))
                ->where('b.id=?', $branch_data['branch_id'])
                ->execute();
    }
    
    public function getOne($id){
        return Doctrine_Query::create()
                ->select('b.*, c.id, g.id')
                ->from('ShopBranches b, b.LookupCollections c, c.LookupGovernorates g')
                ->where('b.id =?', $id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->fetchOne();
    }
    
    public function activateDeactivate($branch_id) {
        $status = false;
        if ($this->isBranchActive($branch_id))
            $status = true;

        Doctrine_Query::create()
                ->update('ShopBranches sb')
                ->set('sb.is_active', '?', $status)
                ->where('sb.id=?', $branch_id)
                ->execute();

        return $status;
    }
    
    private function isBranchActive($branch_id) {
        $q = Doctrine_Query::create()
                ->select('sb.is_active')
                ->from('ShopBranches sb')
                ->where('sb.id=?', $branch_id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->fetchOne();


        if ($q['is_active'])
            return false;
        return true;
    }

    public function deleteBranch($branch_id) {
        Doctrine_Query::create()
                ->update('ShopBranches sb')
                ->set('sb.deleted', '?', true)
                ->where('sb.id=?', $branch_id)
                ->execute();
    }

}