<?php

/**
 * ShopOnlinePresenceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopOnlinePresenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopOnlinePresenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopOnlinePresence');
    }
}