<?php

/**
 * Shops
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Shops extends BaseShops
{
    function addShop(array $shop_data){
        $s = new Shops();
        $s->lang_id = 1;
        $s->category_id = $shop_data['category_id'];
        $s->country_id = $shop_data['country_id'];
        $s->name = $shop_data['shop_name'];
        $s->longitude = $shop_data['longitude'];
        $s->latitude = $shop_data['latitude'];
        $s->city = $shop_data['city'];
        $s->area = $shop_data['area'];
        $s->street = $shop_data['street'];
        $s->tel1 = $shop_data['tel1'];
        $s->tel2 = $shop_data['tel2'];
        $s->fax = $shop_data['fax'];
        $s->website = $shop_data['website'];
        $s->sub_domain = $shop_data['sub_domain'];
        $s->created_at = date('ymdHis');
        $s->save();
        
        return $s->id;
    }
    
    public function updateShop(array $data){
        Doctrine_Query::create()
                ->update('Shops s')
                ->set('s.name', '?', $data['shop_name'])
                ->set('s.longitude', '?', $data['longitude'])
                ->set('s.latitude', '?', $data['latitude'])
                ->set('s.city', '?', $data['city'])
                ->set('s.area', '?', $data['area'])
                ->set('s.street', '?', $data['street'])
                ->set('s.tel1', '?', $data['tel1'])
                ->set('s.tel2', '?', $data['tel2'])
                ->set('s.fax', '?', $data['fax'])
                ->set('s.website', '?', $data['website'])
                ->set('s.updated_at', '?', date('ymdHis'))
                ->where('s.id =?', $data['shop_id'])
                ->execute();
    }
    
    function isSubDomainExist($subDomain){
        $q = Doctrine_Query::create()
                ->select('COUNT(s.id) AS is_exist')
                ->from('Shops s')
                ->where('s.sub_domain =?', $subDomain)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->fetchOne();
        
        if($q['is_exist'] > 0)
            return true;
        return false;
    }
    
    public function getOne($id){
        return Doctrine_Query::create()
                ->select('s.*, op.*')
                ->from('Shops s, s.ShopOnlinePresence op')
                ->where('s.id=?', $id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->fetchOne();
    }
    
    public function getShopAndUserAccount($id){
        return Doctrine_Query::create()
                ->select('s.*, op.*, u.*')
                ->from('Shops s, s.ShopOnlinePresence op, s.Users u')
                ->where('s.id=?', $id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->fetchOne();
    }
    
    public function getLogo($shop_id){
        $q = Doctrine_Query::create()
                ->select('s.logo')
                ->from('Shops s')
                ->where('s.id=?', $shop_id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->fetchOne();
        
        return $q['logo'];
    }
    
    public function getShopCategoryId($id){
        $q = Doctrine_Query::create()
                ->select('s.category_id')
                ->from('Shops s')
                ->where('s.id=?', $id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->fetchOne();
        
        return $q['category_id'];
    }
    
    public function updateLogo($shop_id, $logo){
        Doctrine_Query::create()
                ->update('Shops s')
                ->set('s.logo', '?', $logo)
                ->where('s.id =?', $shop_id)
                ->execute();
    }
}