<?php

/**
 * ShopOfferComponentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopOfferComponentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopOfferComponentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopOfferComponents');
    }
}