<?php

/**
 * ShopBranchesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopBranchesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopBranchesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopBranches');
    }
    
    public static function getAllBranches($shop_id){
        return Doctrine_Query::create()
                ->select('sb.*, m.id, s.id')
                ->from('ShopBranches sb, sb.ShopMenuSubs m, m.Shops s')
                ->where('s.id=?', $shop_id)
                ->andWhere('sb.deleted=0')
                ->orderBy('sb.branch_order ASC')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
    
    public static function getShopBranches($shop_id){
        return Doctrine_Query::create()
                ->select('sb.*, m.id, s.id')
                ->from('ShopBranches sb, sb.ShopMenuSubs m, m.Shops s')
                ->where('s.id=?', $shop_id)
                ->andWhere('sb.deleted=0')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
}