<?php

/**
 * ShopOfferComponents
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShopOfferComponents extends BaseShopOfferComponents
{
    public function addOfferComponents(array $componentsdata){
        $oc = new ShopOfferComponents();
        $oc->offer_id = $componentsdata['offer_id'];
        $oc->item = $componentsdata['item'];
        $oc->type = $componentsdata['type'];
        $oc->created_at = date('ymdHis');
        $oc->save();
    }
    
    public function hardDeleteOffersComponents($shop_id){
        Doctrine_Query::create()
                ->delete('ShopOfferComponents po')
                ->where('po.offer_id IN (SELECT o.id FROM ShopOffers o INNER JOIN o.ShopMenuSubs ms WHERE ms.shop_id='. $shop_id .')')
                ->execute();
    }
}