<?php

/**
 * ShopCategoryFiltersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopCategoryFiltersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopCategoryFiltersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopCategoryFilters');
    }
    
    public static function getCategoryFilters($cat_id){
        return Doctrine_Query::create()
                ->select('f.*')
                ->from('ShopCategoryFilters f')
                ->where('f.cat_id =?', $cat_id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
}