<?php

/**
 * ShopContactsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopContactsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopContactsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopContacts');
    }
}