<?php

/**
 * ShopAboutUs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShopAboutUs extends BaseShopAboutUs
{
    public function getOne($id){
        return Doctrine_Query::create()
                ->select('a.*')
                ->from('ShopAboutUs a')
                ->where('a.id =?', $id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->fetchOne();
    }
    
    public function addAboutUs(array $data){
        $published = false;
        if ($data['published'] == 'yes') {
            $published = true;
        }
        
        $a = new ShopAboutUs();
        $a->sub_id = $data['sub_id'];
        $a->description = $data['description'];
        $a->published = $published;
        $a->created_at = date('ymdHis');
        $a->save();
    }
    
    public function updateAboutUs(array $data){
        $published = false;
        if ($data['published'] == 'yes') {
            $published = true;
        }
        
        Doctrine_Query::create()
                ->update('ShopAboutUs a')
                ->set('a.sub_id', '?', $data['sub_id'])
                ->set('a.description', '?', $data['description'])
                ->set('a.published', '?', $published)
                ->set('a.updated_at', '?', date('ymdHis'))
                ->where('a.id =?', $data['about_us_id'])
                ->execute();
    }
}