<?php

/**
 * ShopProductsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopProductsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopProductsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopProducts');
    }
    
    public static function getAllProducts($shop_id){
        return Doctrine_Query::create()
                ->select('sp.*, m.id, s.id')
                ->from('ShopProducts sp, sp.ShopMenuSubs m, m.Shops s')
                ->where('s.id=?', $shop_id)
                ->andWhere('sp.deleted=0')
                ->orderBy('sp.product_order ASC')
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
    
    public static function searchProducts($keyword){
        return Doctrine_Query::create()
                ->select('p.*, pc.*')
                ->from('ShopProducts p, p.ShopProductComponents pc')
                ->where('p.name LIKE ?', '%' .$keyword . '%')  
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
}