<?php

/**
 * ShopAboutUsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopAboutUsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopAboutUsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopAboutUs');
    }
    
    public static function getAboutUsItems($shop_id){
        return Doctrine_Query::create()
                ->select('a.*, m.name')
                ->from('ShopAboutUs a, a.ShopMenuSubs m, m.Shops s')
                ->where('s.id =?', $shop_id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();
    }
}