<?php

/**
 * ShopAlbums
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShopAlbums extends BaseShopAlbums
{
    public function getOne($id){
        return Doctrine_Query::create()
                ->select('a.*')
                ->from('ShopAlbums a')
                ->where('a.id=?', $id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->fetchOne();
    }
    
    public function addAlbum(array $data){
        $published = false;
        if(isset($data['published']) && $data['published'] == 'yes'){
            $published = true;
        }
        $a = new ShopAlbums();
        $a->sub_id = $data['sub_id'];
        $a->template_id = 1;
        $a->name = $data['name'];
        $a->img = $data['main_img'];
        $a->published = $published;        
        $a->created_at = date('ymdHis');
        $a->save();
    }
    
    public function updateAlbum(array $data){
        $published = false;
        if(isset($data['published']) && $data['published'] == 'yes'){
            $published = true;
        }
        
        Doctrine_Query::create()
                ->update('ShopAlbums a')
                ->set('a.sub_id', '?', $data['sub_id'])
                ->set('a.name', '?', $data['name'])
                ->set('a.img', '?', $data['main_img'])
                ->set('a.published', '?', $published)
                ->set('a.updated_at', '?', date('ymdHis'))
                ->where('a.id =?', $data['album_id'])
                ->execute();
    }
    
    public function activateDeactivate($album_id) {
        $status = false;
        if ($this->isAlbumActive($album_id))
            $status = true;

        Doctrine_Query::create()
                ->update('ShopAlbums a')
                ->set('a.published', '?', $status)
                ->where('a.id=?', $album_id)
                ->execute();

        return $status;
    }
    
    private function isAlbumActive($album_id) {
        $q = Doctrine_Query::create()
                ->select('a.published as is_active')
                ->from('ShopAlbums a')
                ->where('a.id=?', $album_id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->fetchOne();


        if ($q['is_active'])
            return false;
        return true;
    }
    
    public function deleteAlbum($album_id) {
        Doctrine_Query::create()
                ->update('ShopAlbums a')
                ->set('a.deleted', '?', true)
                ->where('a.id=?', $album_id)
                ->execute();
    }
}