<?php

/**
 * UserProductsBasketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserProductsBasketTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserProductsBasketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserProductsBasket');
    }
}