<?php

/**
 * UserProductsBasketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserProductsBasketTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserProductsBasketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserProductsBasket');
    }
    
    public static function getUserProductsBasket($shop_id, $offset = 0, $limit = 10){
        return Doctrine_Query::create()
                ->select('upb.*, r.*, p.name')
                ->from('UserProductsBasket upb, upb.ShopProducts p, p.ShopMenuSubs m, upb.MobileRegistrations r')
                ->where('m.shop_id=?', $shop_id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->offset($offset)
                ->limit($limit)
                ->execute();
    }
    
    public static function getCountUserProductsBasket($shop_id){
        $q = Doctrine_Query::create()
                ->select('COUNT(upb.id) AS total_orders, upb.id, p.id')
                ->from('UserProductsBasket upb, upb.ShopProducts p, p.ShopMenuSubs m')
                ->where('m.shop_id=?', $shop_id)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->fetchOne();
        
        return $q['total_orders'];
    }
    
    public function hardDeleteProductsBasket($shop_id){
        Doctrine_Query::create()
                ->delete('UserProductsBasket pc')
                ->where('pc.product_id IN (SELECT p.id FROM ShopProducts p INNER JOIN p.ShopMenuSubs ms WHERE ms.shop_id='. $shop_id .')')
                ->execute();
    }
}