<?php

/**
 * UserProductsBasket
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserProductsBasket extends BaseUserProductsBasket
{
    public function addUserProductToBasket(array $data){
        $b = new UserProductsBasket();
        $b->user_id = $data['user_id'];
        $b->product_id = $data['product_id'];
        $b->quantity = $data['quantity'];
        $b->created_at = $data['created_at'];
        $b-save();
    }
}